services:
  api:
    build: .
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: