version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    env_file: .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: