# Generated by Django 5.1.4 on 2025-02-18 16:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(db_comment='UUID created by backend and given to frontend to track current session, expires after a day', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Start time of the session')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.UUIDField(db_comment='UUID to track a user in the cookies/local storage', default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='Start time of the session')),
            ],
        ),
        migrations.CreateModel(
            name='ReferredFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.PositiveSmallIntegerField(choices=[(1, 'LinkedIn'), (2, 'YouTube'), (3, 'GitHub')], db_comment="The link referred from ['LinkedIn', 'YouTube', 'GitHub']", default=0, editable=False)),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time that the user was referred to the website')),
                ('session', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='PageAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveSmallIntegerField(choices=[(1, 'home'), (2, 'blogs'), (3, 'projects'), (4, 'blog'), (5, 'project'), (6, 'analytics')], db_comment="The page viewed ['home', 'blogs', 'projects']", default=0, editable=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time that the link was taken')),
                ('session', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='LinksTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.PositiveSmallIntegerField(choices=[(1, 'LinkedIn'), (2, 'YouTube'), (3, 'GitHub')], db_comment="The link taken ['LinkedIn', 'YouTube', 'GitHub']", default=0, editable=False)),
                ('taken_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time that the link was taken')),
                ('session', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_type', models.PositiveSmallIntegerField(choices=[(1, 'blog'), (2, 'project')], db_comment="The link taken ['unknown', 'blog', 'project']", default=0, editable=False)),
                ('article_id', models.PositiveSmallIntegerField(db_comment='The id of the article', db_default=-1, editable=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time that the link was taken')),
                ('session', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(db_comment='the user of the session', editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
