name: Deploy to DigitalOcean

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                known_hosts: "placeholder"
            
          - name: Add known hosts
            run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

          - name: Copy files
            run: |
              scp -r ./* root@${{ secrets.DROPLET_IP }}:/root/app/
              scp .env root@${{ secrets.DROPLET_IP }}:/root/app/
    
          - name: Deploy
            run: |
              ssh root@${{ secrets.DROPLET_IP }} "cd /root/app && \
              docker-compose down && \
              docker-compose up -d --build"