name: Deploy to DigitalOcean

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                known_hosts: "placeholder"
            
          - name: Add known hosts
            run: ssh-keyscan -H ${{ secrets.DROPLET_IP }} >> ~/.ssh/known_hosts

          - name: Sync files
            run: |
                ssh root@${{ secrets.DROPLET_IP }} "cd /root/app && rm -rf \$(ls -A | grep -Ev '^(certbot|nginx)$')"
                scp -r ./* root@${{ secrets.DROPLET_IP }}:/root/app/

          - name: Create .env file
            run: |
                ssh root@${{ secrets.DROPLET_IP }} "cat > /root/app/.env << 'EOF'
                MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
                MYSQL_USER=${{ secrets.MYSQL_USER }}
                MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
                MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
                SUPERUSER_USERNAME=${{ secrets.SUPERUSER_USERNAME }}
                SUPERUSER_EMAIL=${{ secrets.SUPERUSER_EMAIL }}
                SUPERUSER_PASSWORD=${{ secrets.SUPER_USER_PASSWORD }}
                DROPLET_IP=${{ secrets.DROPLET_IP }}
                EOF"
    
          - name: Deploy
            run: |
                ssh root@${{ secrets.DROPLET_IP }} "cd /root/app && \
                docker-compose down && \
                docker-compose up -d --build"